name: iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Посмотреть файлы
        run: |
          echo "--- ЧТО ЛЕЖИТ В КОРНЕ ---"
          ls -la
          echo "--- ПОЛНЫЙ ПОИСК XCODE ПРОЕКТОВ ---"
          find . -name "*.xcodeproj
